services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile   # Point to the actual file
    container_name: my-custom-node-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_NAME=food_ordering
      - DB_USER=postgres
      - DB_PASSWORD=devpassword123
    depends_on:
      - db
    volumes:
      - ./frontend:/app/public
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=food_ordering
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devpassword123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/sample-data.sql:/docker-entrypoint-initdb.d/2-data.sql
    restart: unless-stopped

volumes:
  db_data:

